### ISSUE TITLE
Element is not connected, implicit start/end are incorrect in ad-hoc subprocess

### ISSUE THREAD

**Issue by barmac** [bpmn-io/bpmnlint#180]
### Describe the Bug

Rules on implicit start/end, element not connected are misleading in ad-hoc subprocess. They should not be applied at all.

![Image](https://github.com/user-attachments/assets/1da3ac87-d925-44eb-b024-905c459fbd1c)

### Steps to Reproduce

1. Create ad-hoc subprocess
2. Place a task inside
3. now this happens

### Expected Behavior

Rules should not apply.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by Buckwich** [comment]
@barmac would https://github.com/camunda/camunda-modeler/pull/4876 the implicit start/end part of this?

**Comment by nikku** [comment]
Fixed via https://github.com/bpmn-io/bpmnlint/pull/176, I believe.

**Comment by barmac** [comment]
It's not fixed. The rules changed in #176 are different from the rules in this report. Cf. the failing test cases: https://github.com/bpmn-io/bpmnlint/tree/test-cases-for-180

**Comment by Buckwich** [comment]
The `no-disconnect` rules affects `Tasks`, `Subproccesses`, `Gateways`, and `Event`. Shall I only disable it for tasks or also subprocesses? For Gateways and Events we can keep it
